protected/controllers/ContentController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\TrArtikel;
use app\components\Logic;
use yii\data\ActiveDataProvider;

class ContentController extends Controller
{
    public function actionIndex($judul)
    {
		$artikel = TrArtikel::find()->andWhere('slug_judul = :param1', [':param1'=>$judul])->one();
		$artikel->total_views = $artikel->total_views + 1;
		$artikel->save();
		
		$expjudul = explode(' ',$artikel->judul);
		$impjudul = implode(',',$expjudul);
		$url = explode('embed/', Logic::videoPertama($artikel->isi));
		
		\Yii::$app->view->registerMetaTag(['property' => 'fb:app_id', 'content' => '884284381724333']);
		\Yii::$app->view->registerMetaTag(['property' => 'og:url', 'content' => $artikel->judul]);
		\Yii::$app->view->registerMetaTag(['property' => 'og:title', 'content' => $artikel->judul]);
		\Yii::$app->view->registerMetaTag(['property' => 'og:type', 'content' => 'article']);
		\Yii::$app->view->registerMetaTag(['property' => 'og:description', 'content' => substr(strip_tags(Logic::removeNbsp($artikel->isi)), 0, 150)]);
		\Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => substr(strip_tags(Logic::removeNbsp($artikel->isi)), 0, 150)]);
		\Yii::$app->view->registerMetaTag(['name' => 'keywords', 'content' => $impjudul.' (Berita terbaru, berita terkini, berita viral, berita kisaran, berita medan, berita sumut, berita sumatera utara, berita kriminal, berita kesehatan, berita antariksa, berita olahraga, berita travelling, video youtube, berita bisnis, berita  kesehatan, berita di indonesia dan internasional, nurkarim nehe, asmi group, jernih memandang sekitar, tempat kita jumpa)']);
		
		if(Logic::gambarPertama($artikel->isi) == ''){
            if(Logic::videoPertama($artikel->isi) != ''){
				\Yii::$app->view->registerMetaTag(['property' => 'og:video', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:secure_url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:type', 'content' => 'video/mp4']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:width', 'content' => '1280']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => '780']);
            }else{
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => 'http://inibabad.com/themes/customilham/assets/imgs/logoinibabad.png']);
            }
        }else{
			if(Logic::videoPertama($artikel->isi) == ''){
				$gambarall = Logic::gambarAll($artikel->isi);
				foreach($gambarall as $gdx=>$grow){
					\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => $grow]);
				}
			}else{
				\Yii::$app->view->registerMetaTag(['property' => 'og:video', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:secure_url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:type', 'content' => 'video/mp4']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:width', 'content' => '1280']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => 'https://i.ytimg.com/vi/'.$url[1].'/hqdefault.jpg']);
			}
        }
		
        return $this->render('index', [
			'artikel'=>$artikel
		]);
    }
}

protected/controllers/ListController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\Menu;
use app\models\TrArtikel;
use app\components\Logic;
use yii\data\ActiveDataProvider;

class ListController extends Controller
{
    public function actionIndex($name)
    {
		$menu = Menu::find()->andWhere('slug_name = :param1', [':param1'=>$name])->one();
		
		$artikel = TrArtikel::find()->andWhere('menu_id = :param1', [':param1'=>$menu->id])->orderBy(['id'=>SORT_DESC])->one();
		$expjudul = explode(' ',$artikel->judul);
		$impjudul = implode(',',$expjudul);
		$url = explode('embed/', Logic::videoPertama($artikel->isi));
		if($menu->is_video == true){
			\Yii::$app->view->registerMetaTag(['property' => 'og:title', 'content' => $menu->name]);
			
		}else{
			\Yii::$app->view->registerMetaTag(['property' => 'og:title', 'content' => $menu->name.' - '.$artikel->judul]);			
		}
		\Yii::$app->view->registerMetaTag(['property' => 'fb:app_id', 'content' => '884284381724333']);
		\Yii::$app->view->registerMetaTag(['property' => 'og:url', 'content' => Yii::$app->request->url]);
		\Yii::$app->view->registerMetaTag(['property' => 'og:type', 'content' => 'article']);
		\Yii::$app->view->registerMetaTag(['property' => 'og:description', 'content' => substr(strip_tags(Logic::removeNbsp($artikel->isi)), 0, 150)]);
		\Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => substr(strip_tags(Logic::removeNbsp($artikel->isi)), 0, 150)]);
		\Yii::$app->view->registerMetaTag(['name' => 'keywords', 'content' => $impjudul.' (Berita terbaru, berita terkini, berita viral, berita kisaran, berita medan, berita sumut, berita sumatera utara, berita kriminal, berita kesehatan, berita antariksa, berita olahraga, berita travelling, video youtube, berita bisnis, berita  kesehatan, berita di indonesia dan internasional, nurkarim nehe, asmi group, jernih memandang sekitar, tempat kita jumpa)']);
		
		if(Logic::gambarPertama($artikel->isi) == ''){
            if(Logic::videoPertama($artikel->isi) != ''){
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:secure_url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:type', 'content' => 'text/html']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:width', 'content' => '1280']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => '780']);
            }else{
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => 'http://inibabad.com/themes/customilham/assets/imgs/logoinibabad.png']);
            }
        }else{
			if(Logic::videoPertama($artikel->isi) == ''){
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => Logic::gambarPertama($artikel->isi)]);
			}else{
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:secure_url', 'content' => Logic::videoPertama($artikel->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:type', 'content' => 'text/html']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:width', 'content' => '1280']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => 'https://i.ytimg.com/vi/'.$url[1].'/hqdefault.jpg']);
			}
        }
		
		if($menu->is_video == true){
			$dataProvider = new ActiveDataProvider([
				'query' => TrArtikel::find()
					->andWhere(['like', 'isi', '%iframe%', false]),
				'pagination' => [
					'pageSize' => 10,
				],
				'sort' => [
					'defaultOrder' => [
						'id' => SORT_DESC
					]
				],
			]);
		}else{
			$dataProvider = new ActiveDataProvider([
				'query' => TrArtikel::find()->andWhere('menu_id = :param1', [':param1'=>$menu->id]),
				'pagination' => [
					'pageSize' => 10,
				],
				'sort' => [
					'defaultOrder' => [
						'id' => SORT_DESC
					]
				],
			]);
		}	
		
        return $this->render('index', [
			'dataProvider'=>$dataProvider,
			'menu'=>$menu
		]);
    }
}

protected/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;
use app\models\TrArtikel;
use app\models\Menu;
use app\components\Logic;
use app\components\Api;

class SiteController extends Controller
{
	public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }	

    public function actionIndex()
    {
		$as = TrArtikel::find()->orderBy(['id'=>SORT_DESC])->one();
		$expjudul = explode(' ',$as->judul);
		$impjudul = implode(',',$expjudul).' (Berita terbaru, berita terkini, berita viral, berita kisaran, berita medan, berita sumut, berita sumatera utara, berita kriminal, berita kesehatan, berita antariksa, berita olahraga, berita travelling, video youtube, berita bisnis, berita  kesehatan, berita di indonesia dan internasional, nurkarim nehe, asmi group, jernih memandang sekitar, tempat kita jumpa)';
		$url = explode('embed/', Logic::videoPertama($as->isi));
		
		\Yii::$app->view->registerMetaTag(['property' => 'fb:app_id', 'content' => '884284381724333']);
		\Yii::$app->view->registerMetaTag(['property' => 'og:url', 'content' => Yii::$app->request->url]);
		\Yii::$app->view->registerMetaTag(['property' => 'og:title', 'content' => $as->judul]);
		\Yii::$app->view->registerMetaTag(['property' => 'og:type', 'content' => 'article']);
		\Yii::$app->view->registerMetaTag(['property' => 'og:description', 'content' => substr(strip_tags(Logic::removeNbsp($as->isi)), 0, 150)]);
		\Yii::$app->view->registerMetaTag(['name' => 'description', 'content' => substr(strip_tags(Logic::removeNbsp($as->isi)), 0, 150)]);
		\Yii::$app->view->registerMetaTag(['name' => 'keywords', 'content' => $impjudul]);
		
		if(Logic::gambarPertama($as->isi) == ''){
            if(Logic::videoPertama($as->isi) != ''){
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:url', 'content' => Logic::videoPertama($as->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:secure_url', 'content' => Logic::videoPertama($as->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:type', 'content' => 'text/html']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:width', 'content' => '1280']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => '780']);
            }else{
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => 'http://inibabad.com/themes/customilham/assets/imgs/logoinibabad.png']);
            }
        }else{
			if(Logic::videoPertama($as->isi) == ''){
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => Logic::gambarPertama($as->isi)]);
			}else{
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:url', 'content' => Logic::videoPertama($as->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:secure_url', 'content' => Logic::videoPertama($as->isi)]);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:type', 'content' => 'text/html']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:video:width', 'content' => '1280']);
				\Yii::$app->view->registerMetaTag(['property' => 'og:image', 'content' => 'https://i.ytimg.com/vi/'.$url[1].'/hqdefault.jpg']);
			}
        }
		
        return $this->render('index');
    }
	
	public function actionLatestvideo()
    {
		$name = $_POST['menu'];
		if(!empty($name)){
			$menu = Menu::find()->andWhere('slug_name = :param1', [':param1'=>$name])->one();
			if(empty($menu)){
				 throw new \yii\web\HttpException(404, 'The page you were looking for could not be found. You may have typed the address incorrectly or you may have used an outdated link, or that page is traveling on Mars :).');
			}
		}
		
        if (Yii::$app->request->isAjax) {
            try {
                return $this->renderPartial('_latestvideo', [
					'menu'=>$menu
				]);
            } catch (\Exception $e) {
                return $e->getMessage().'Terjadi kesalahan! Silahkan hubungi administrator';
            }
        }
    }
	
	public function actionLatestpost()
    {
        if (Yii::$app->request->isAjax) {
            try {
                return $this->renderPartial('_latestpost');
            } catch (\Exception $e) {
                return $e->getMessage().'Terjadi kesalahan! Silahkan hubungi administrator';
            }
        }
    }
	
	public function actionPopulerpost()
    {
		$name = $_POST['menu'];
		if(!empty($name)){
			$menu = Menu::find()->andWhere('slug_name = :param1', [':param1'=>$name])->one();
			if(empty($menu)){
				 throw new \yii\web\HttpException(404, 'The page you were looking for could not be found. You may have typed the address incorrectly or you may have used an outdated link, or that page is traveling on Mars :).');
			}
		}
		
        if (Yii::$app->request->isAjax) {
            try {
                return $this->renderPartial('_populerpost', [
					'menu'=>$menu
				]);
            } catch (\Exception $e) {
                return $e->getMessage().'Terjadi kesalahan! Silahkan hubungi administrator';
            }
        }
    }
	
	public function actionCorona()
    {
        if (Yii::$app->request->isAjax) {
            try {
				$negara = $_POST['negara'];
				strip_tags($negara);
				$apisingle = Api::datacoronasingle($negara);
				$apiall = Api::datacoronaall();
				$dataall = [];
				foreach($apiall as $adx=>$arow){
					$dataall['cases'] += $arow['cases'];
					$dataall['todayCases'] += $arow['todayCases'];
					$dataall['deaths'] += $arow['deaths'];
					$dataall['todayDeaths'] += $arow['todayDeaths'];
					$dataall['recovered'] += $arow['recovered'];
					$dataall['todayRecovered'] += $arow['todayRecovered'];
					$dataall['active'] += $arow['active'];
				}
				
                return $this->renderPartial('_corona', [
					'apisingle'=>$apisingle,
					'dataall'=>$dataall
				]);
            } catch (\Exception $e) {
                return $e->getMessage().'Terjadi kesalahan! Silahkan hubungi administrator';
            }
        }
    }
	
	public function actionLoadvideo()
    {
        if (Yii::$app->request->isAjax) {
            try {
				$dataurl = $_POST['dataurl'];
				strip_tags($dataurl);
				
                return $this->renderPartial('_loadvideo', [
					'dataurl'=>$dataurl
				]);
            } catch (\Exception $e) {
                return $e->getMessage().'Terjadi kesalahan! Silahkan hubungi administrator';
            }
        }
    }
}

protected/views/site/_latestvideo.php
<?php
	use Yii;
	use app\models\TrArtikel;
	use app\models\Menu;
	use app\components\Logic;
	use app\components\Api;
	use yii\helpers\Url;
	// var_dump($menu->id);exit;
	
	if(!empty($menu)){
		$artikelvideo = TrArtikel::find()->andWhere('menu_id = :param1 AND isi REGEXP \'iframe\' = :param2', [':param1'=>$menu->id, ':param2'=>1])->limit(5)->orderBy(['created_date'=>SORT_DESC])->all();
	}else{
		$artikelvideo = TrArtikel::find()->andWhere('isi REGEXP \'iframe\' = :param1', [':param1'=>1])->limit(5)->orderBy(['created_date'=>SORT_DESC])->all();		
	}
	$video = [];
	foreach($artikelvideo as $vdx=>$vrow){
		if(Logic::videoPertama($vrow->isi) != ''){
			$video[] = Logic::videoPertama($vrow->isi);
			$artjudul[] = $vrow->slug_judul;
		}
	}
	$listvideo = $video;

	if(!empty($listvideo)){
		foreach($listvideo as $vdx=>$vrow){ 
		$expvideo = explode('/',$vrow);
		$descvideo = Api::videoyoutube(end($expvideo));
		$bg = $descvideo['items'][0]['snippet']['thumbnails']['high']['url'];
		$title = $descvideo['items'][0]['snippet']['title'];
		$created_by = $descvideo['items'][0]['snippet']['channelTitle'];
		$created_date = $descvideo['items'][0]['snippet']['publishedAt'];
		$views = $descvideo['items'][0]['statistics']['viewCount'];
		$loves = $descvideo['items'][0]['statistics']['likeCount'];
		// echo '<pre>';
		// var_dump($descvideo['items'][0]);
		if(!empty($title)){
?>
			<article class="bg-white border-radius-15 mb-30 p-10">
				<div class="img-hover-slide border-radius-15 mb-10 position-relative overflow-hidden" style="min-height: 150px !important;">
					<a onclick="loadvideo('<?php echo $title; ?>', '<?php echo $vrow; ?>')" href="javascript:void(0)" data-toggle="modal" data-target="#loadmodal" data-keyboard="false" data-backdrop="static">
						<div class="thumb-overlay img-hover-slide border-radius-15 position-relative" style="background-image: url(<?php echo $bg; ?>); background-position:center !important;min-height:150px !important;"></div>
						<div style="display:none">Video Background - <?php echo $title; ?></div>
					</a>
				</div>
				<div class="pl-10 pr-10">
					<h6 class="post-title mb-15"><a href="<?php echo Url::to(['/content/index', 'judul'=>rawurlencode($artjudul[$vdx])]); ?>"><span style="display:none;">Video - </span><?php echo $title; ?></a></h6>
					<div class="entry-meta meta-1 font-x-small color-grey float-left text-uppercase mb-10">
						<div class="mb-10">
							<span class="post-by"><i class="icofont icofont-user"></i> Oleh <?php echo $created_by; ?></span>
							<span class="post-by"><i class="icofont icofont-eye"></i><?php echo NUMBER_FORMAT($views); ?></span>
							<span class="post-by"><i class="icofont icofont-love"></i><?php echo NUMBER_FORMAT($loves); ?></span>
						</div>
						<div>
							<span class="post-by"><i class="icofont icofont-calendar"></i> Diposting <?php echo Logic::convertDate($created_date); ?></span>
						</div>
					</div>
				</div>
			</article>
			
			<script>
				function loadvideo(judul, url){
					$('#loadmodal').find('.modal-header .modal-title').html('<i class="icofont icofont-ui-video-chat"></i> '+judul);
					
					$.ajax({
						url: '<?php echo Url::toRoute(['site/loadvideo']); ?>',
						type: 'POST',
						dataType: "html",
						data:{
							dataurl:url
						},
						beforeSend: function() {
							$("#loadermodal").html('<div class="loader-box"><div class="loader-30"></div></div>');
							$("#datamodal").html('');
						},
						success: function(data){
							$("#datamodal").html(data);
						},
						complete: function(){
							$("#datamodal").show();
							$("#loadermodal").html('');
						},
						error: function (xhr, ajaxOptions, thrownError) {
							var pesan = xhr.status + " " + thrownError + "\n" +  xhr.responseText;
							$("#datamodal").html('<div class="alert alert-danger inverse alert-dismissible fade show m-0" role="alert"><i class="icofont icofont-warning-alt"></i> '+pesan+'</div>');
						},
					});
				}
			</script>
<?php 
			}
		}
	}else{
?>
		<article class="bg-white border-radius-15 mb-30 p-10 wow fadeIn  animated" style="visibility: visible; animation-name: fadeIn;">
			<div class="pl-10 pr-10">
				<h6 class="post-title mb-15"><a href="single.html">Video terbaru tidak ditemukan</a></h6>
			</div>
		</article>
<?php 
	} 
?>
	

protected/views/site/_populerpost.php
<?php
	use Yii;
	use app\models\TrArtikel;
	use app\models\Menu;
	use app\components\Logic;
	use yii\helpers\Url;

	if(!empty($menu)){
		$artikellock = TrArtikel::find()->select('GROUP_CONCAT(id) dataid')->andWhere('created_date BETWEEN DATE_SUB(NOW(), INTERVAL 60 DAY) AND NOW()')->andWhere('menu_id = :param1', [':param1'=>$menu->id])->orderBy(['created_date'=>SORT_DESC])->one(); 
	}else{
		$artikellock = TrArtikel::find()->select('GROUP_CONCAT(id) dataid')->andWhere('created_date BETWEEN DATE_SUB(NOW(), INTERVAL 60 DAY) AND NOW()')->orderBy(['created_date'=>SORT_DESC])->one(); 
	}
	$artikelpopuler = TrArtikel::find()->andWhere('id IN ('.$artikellock->dataid.')')->orderBy(['total_views'=>SORT_DESC])->limit(5)->all(); 
	if(!empty($artikelpopuler)){
		$rank = 0;
		foreach($artikelpopuler as $pdx=>$prow){
			$rank += 1;
			$backgroundpopuler = Logic::gambarPertama($prow->isi);
?>
			<article class="pl-10 pt-10 pr-10" style="visibility: visible; animation-name: fadeIn;">
				<div class="pl-10 pr-10">
					<div class="entry-meta mb-15">
						<a class="entry-meta meta-0" href="<?php echo Url::to(['/list/index', 'name'=>$prow->menu->name]); ?>"><span class="post-in post-in btn btn-outline-danger font-x-small font-x-small"><span style="display:none;">Menu - Populer - <?php echo substr($prow->judul,0,50); ?> </span> <?php echo $prow->menu->name; ?></span></a>
					</div>
					<h6 class="post-title text-limit-2-row mb-15">#<?php echo $rank; ?> <i class="icofont icofont-trophy text-warning"></i> <a href="<?php echo Url::to(['/content/index', 'judul'=>$prow->slug_judul]); ?>"><span style="display:none;">Judul - Populer - <?php echo substr($prow->judul,0,50); ?> </span><?php echo $prow->judul; ?></a></h6>
					<div class="entry-meta meta-1 font-x-small color-grey text-uppercase mb-10">
						<div class="mb-10">
							<span class="post-on"><i class="icofont icofont-calendar"></i> <?php echo $prow->created_date; ?></span>
							<span class="post-on"><i class="icofont icofont-eye"></i> <?php echo NUMBER_FORMAT($prow->total_views); ?></span>
						</div>
					</div>
					<hr class="wp-block-separator is-style-wide mb-0">
				</div>
			</article>
<?php 
		}
	}else{ 
?>	
		<article class="bg-white border-radius-15 mb-30 p-10 wow fadeIn  animated" style="visibility: visible; animation-name: fadeIn;">
			<div class="pl-10 pr-10">
				<h6 class="post-title mb-15"><a href="single.html">Postingan terpopuler tidak ditemukan</a></h6>
			</div>
		</article>
<?php } ?>

protected/views/site/index.php
<?php
	use Yii;
	use app\models\TrArtikel;
	use app\models\Menu;
	use app\components\Logic;
	use yii\helpers\Url;
	
	$slider = Logic::hasSlider(10);
?>

<title>Inibabad.com - Portal Berita Terbaru Hari Ini, Jernih Memandang Sekitar, Tempat Kita Jumpa</title>

<span style="display:none"><h1>INIBABAD - JERNIH MEMANDANG SEKITAR</h1></span>

<div class="row mb-15">
	<div class="col-md-12">
		<div class="widget-header position-relative mb-30">
			<span class="widget-title mb-0"></span>
		</div>
		<div class="post-carausel-1 post-module-1 row">
			<?php foreach($slider['hasil'] as $ddx=>$drow){ ?>
				<div class="col">
					<div class="slider-single bg-white p-10 border-radius-15">
						<div class="img-hover-scale border-radius-10">
							<a href="<?php echo Url::to(['/content/index', 'judul'=>$drow['slug_judul']]); ?>">
								<div class="thumb-overlay img-hover-slide-depan border-radius-15" style="background-image: url(<?php echo $drow['gambar']; ?>)"></div>
								<div style="display:none">Background Slider - <?php echo $drow['menu']; ?> - <?php echo substr($drow['judul'],0,50); ?></div>
							</a>
						</div>
						
						<div class="entry-meta meta-0 font-small mt-15 mb-15">
							<a href="<?php echo Url::to(['/list/index', 'name'=>$drow['slug_name']]); ?>"><span class="post-cat bg-danger color-white"><?php echo $drow['menu_icon']; ?> <span style="display:none">Judul Slider - <?php echo $drow['menu']; ?> - <?php echo substr($drow['judul'],0,50); ?></span><?php echo $drow['menu']; ?></span></a>
						</div>
						<h6 class="post-title text-limit-2-row">
							<a href="<?php echo Url::to(['/content/index', 'judul'=>$drow['slug_judul']]); ?>"><?php echo $drow['judul']; ?></a>
						</h6>
						<div class="entry-meta meta-1 font-x-small mt-10 pr-5 pl-5 text-muted">
							<div>
								<span class="mr-5 text-muted"><i class="icofont icofont-calendar"></i></span><?php echo $drow['created_date']; ?>
								<span class="mr-5"><i class="icofont icofont-eye"></i></span><?php echo $drow['total_views']; ?>
							</div>
						</div>
							
						
					</div>
				</div>
			<?php } ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 primary-sidebar sticky-sidebar sidebar-left order-1 order-md-1">
		<div class="latest-post mb-15">
			<div class="widget-header position-relative mb-10" style="border-bottom: 1px solid #d4cfcf;">
				<div class="row">
					<div class="col-12">
						<h4 class="widget-title mb-0"><i class="icofont icofont-dna-alt-1"></i> Perkembangan Virus <span>Corona</span></h4>
					</div>
				</div>
			</div>
			<div id="loadercorona"></div>
			<div class="post-aside-style-3 bg-white border-radius-15" id="datacorona"></div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-3 col-md-3 primary-sidebar sticky-sidebar sidebar-left order-2 order-md-1">
		<?php echo $this->render('_arsipberita', ['menu'=>$menu]); ?>
		
		<div class="latest-post mb-50">
			<div class="widget-header position-relative mb-10" style="border-bottom: 1px solid #d4cfcf;">
				<div class="row">
					<div class="col-12">
						<h4 class="widget-title mb-0"><i class="icofont icofont-ui-video-play"></i> Video <span>Terbaru</span></h4>
					</div>
				</div>
			</div>
			<div id="loaderlatestvideo"></div>
			<div class="post-aside-style-3" id="datalatestvideo"></div>
		</div>
	</div>
	<div class="col-lg-9 col-md-9 order-1 order-md-2">
		<div class="row">
			<div class="col-lg-8 col-md-12">
				<?php echo $this->render('_latestpost'); ?>
			</div>
			<div class="col-lg-4 col-md-12 primary-sidebar sticky-sidebar sidebar-right order-2 order-md-1">
				<div class="sidebar-widget mb-30">
					<div class="widget-header position-relative mb-10" style="border-bottom: 1px solid #d4cfcf;">
						<div class="row">
							<div class="col-12">
								<h4 class="widget-title mb-0">Postingan <span>terpopuler</span></h4>
							</div>
						</div>
					</div>
					<div id="loaderpopulerpost"></div>
					<div class="post-aside-style-3 bg-white border-radius-15" id="datapopulerpost"></div>
				</div>	
			</div>	
		</div>
	</div>	
</div>

<script>
	$(document).ready(function() {
		showcorona('Indonesia', '<?php echo Url::toRoute(['/site/corona']); ?>');
		showlatestvideo(null, '<?php echo Url::toRoute(['/site/latestvideo']); ?>');
		showpopulerpost(null, '<?php echo Url::toRoute(['/site/populerpost']); ?>');
	});
</script>